FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Aspire.WebApp/Aspire.WebApp.csproj", "Aspire.WebApp/"]
RUN dotnet restore "Aspire.WebApp/Aspire.WebApp.csproj"
COPY . .
WORKDIR "/src/Aspire.WebApp"
RUN dotnet build "Aspire.WebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Aspire.WebApp.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Aspire.WebApp.dll"]
